### PR TITLE
Better `to` support

### LINKED ISSUE #160: Socket doesn't have to function
When creating a socket instance, we can't call `socket.to` directly, because it doesn't exist.
Also, there's no support for chaining `.to()` calls.

I have already written code to fix this, will do a pull-request.

### PR DESCRIPTION
**Pull request by publicJorn**
Fixes #160 

- Adds to/in to socket-io. [socket-to-room](https://socket.io/docs/server-api/#socket-to-room)
- Adds possibility to chain to calls on server.
- Added tests for both

### CODE REVIEW

**Comment by thoov** [comment]
Thanks for this! I noticed that yarn.lock was modified but I didn't see anything was updated on package.json. Do you know what changed on it?

**Comment by publicJorn** [comment]
Hmm that's odd, maybe that's why the build failed?
Still had my terminal open, so I could check the history. I did as described in the readme.
But after the `yarn install` I got a message that my yarn needed to be updated, so (still in the project dir) I did a `brew upgrade yarn`. Maybe that changed it.

As for the rest I only ran the test and build scripts.

**Comment by thoov** [comment]
@publicJorn Hmm. I just upgraded yarn and then ran yarn install on master and it generated a different yarn.lock so I think the one you have in this PR is fine. Not sure what changed though. I looked at the build failure and right now it seems like its failing because of lint reasons. Can you run `yarn lint` and fix those?

**Comment by publicJorn** [comment]
Oops.. overlooked that one. Lint errors fixed.
Hope this works for you

**Pull request merged**
