### PR TITLE
MockSocket should implement EventTarget methods

### PR DESCRIPTION
**Pull request by vlizard**
According to [WebSocket spec](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket), WebSocket inherits EventTarget so it should implement `addEventListener`, `removeEventListener` and `dispatchEvent` methods. Some libraries/frameworks (e.g. [Reactive Extensions](https://github.com/Reactive-Extensions/RxJS-DOM/blob/master/src/websocket.js)) use them. The proposed implementation is not complete as it does not handle third parameter of `addEventListener`/`removeEventListener` methods but I believe it should be enough for mocking purposes.

### CODE REVIEW

**Comment by thoov** [comment]
@vlizard Awesome work! Thanks :+1:

**Comment by thoov** [comment]
@vlizard I will bump the npm/bower versions to 0.4 which will have your changes.

**Comment by vlizard** [comment]
Cool! Thanks for this great library.

**Comment by vlizard** [comment]
@thoov It seems new version was not published to npm registry... Could you please do it?

**Comment by thoov** [comment]
@vlizard Thats what I forgot. There should be 0.4.0 out now with your changes.

**Comment by vlizard** [comment]
@thoov Thank you!

**Pull request merged**
