### PR TITLE
Implement a socket.io style interface

### PR DESCRIPTION
**Pull request by bdvholmes**
As described in #17, we require the socket to respond to event subscriptions:

```js
mockSocket.on('chat message', function(e) {
  console.log(e.data); // 'hello'
});

mockServer.emit('chat message', 'hello');
```

I've **not actually tested** with this a socket.io application but it would be good to get your initial thoughts on this first.

### CODE REVIEW

**Comment by bdvholmes** [comment]
cc @samselikoff

**Comment by thoov** [comment]
Thanks @bdvholmes for the PR. This looks like a good start! It would also be very beneficial to add room & namespace support (http://socket.io/docs/rooms-and-namespaces/)

**Comment by bdvholmes** [comment]
Sure thing :+1:

**Comment by samselikoff** [comment]
To establish a connection Socket.io starts out with a GET request that looks like this:

    GET http://localhost:4200/socket.io/?EIO=3&transport=polling&t=1431546178348-0

The line is [here](https://github.com/Automattic/socket.io-client/blob/master/socket.io.js#L2925). We'll need to mock a response out to this as well, to establish the handshake - correct?

**Comment by bdvholmes** [comment]
@samselikoff surely we don't have to worry about this if we're mocking out the client library as well. We're trying to get `MockSocket` to respond to the same interface as a global `io` on the client.

**Comment by samselikoff** [comment]
Ah I see, so if my app uses window.io, I'll need to inject that instead, so I can inject the mock client during testing?

**Comment by bdvholmes** [comment]
Exactly, something like:

    io.Socket = MockSocket;

**Comment by samselikoff** [comment]
Not sure if this is the public socket.io api but one of my apps was doing

```js
window.io.connect(':4545/api')
```

but this doesn't work with the current implementation (i.e. no `ws:` protocol or host name).

**Comment by samselikoff** [comment]
also, seems [socket.io's docs](http://socket.io/docs/client-api/#io(url:string,-opts:object):socket) recommend connecting like this now:

```js
window.io('localhost:4545')
```

so we should support that too

**Comment by thoov** [comment]
@samselikoff We should support `io('some_url')` and ideally it would be something like this:

```js
window.io = MockSocket;
var socket = io('example.com');
```

**Comment by samselikoff** [comment]
@bdvholmes socket.io's client interface is actually not

```js
mockSocket.on('chat message', function(e) {
  console.log(e.data); // 'hello'
});
```

it's

```
mockSocket.on('chat message', function(e) {
  console.log(e); // 'hello'
});
```

i.e. there's no `event.data`, it's just `data` that gets passed to the callback. Perhaps we'll need a config option that the user can set to let mock-socket know it wants socket.io-style messages?

**Comment by bdvholmes** [comment]
I could totally bake that in. I'm Having a bash at finishing this today.

Enviado desde mi iPhone

**Comment by samselikoff** [comment]
sweet, I can help too. let me know, ill be on irc

**Comment by bdvholmes** [comment]
@thoov @samselikoff the branch should be working well now, with the exception of rooms / namespaces. What do you think of this interface:

```js
window.io = MockSocketIO;
var socket = io('example.com');
```

**Comment by thoov** [comment]
@bdvholmes
```js
window.io = MockSocketIO;
var socket = io('example.com');
```
I think that looks great. I will play around with the branch this weekend.

**Comment by bdvholmes** [comment]
@thoov If you could try it out on a working project that would be much appreciated, I'm hoping to finish out the rooms and namespace stuff tomorrow.

I've set up some example repos to test this with:

+ https://github.com/bdvholmes/ember-socketio-chat
+ https://github.com/bdvholmes/ember-socketio-server

**Comment by samselikoff** [comment]
lgtm as well

**Comment by thoov** [comment]
I created this very simple page:

```html
<html>
	<head>
		<script src="dist/mock-socket.js" charset="utf-8"></script>
	</head>
	<body>
		<script type="text/javascript">
			window.io = MockSocketIO;
			var socket = io('http://testing.com');

			socket.on('connection', function () {
				debugger;
			});
		</script>
	</body>
</html>
```
And I am seeing these JS errors:

screen shot 2015-05-26 at 11 24 47 am

**Comment by bdvholmes** [comment]
@thoov just got round to this. So the thing that is undefined here is the service. Is it intended that you can create a socket client without setting up MockServer first?

MockSocketIO is a thin wrapper to MockSocket so I don't think this would work in the normal case.

I've had a go putting together a basic test and it seems to work fine. See bdvholmes/ember-socketio-chat@4ae9402

I'll testing it a bit more rigorously shortly.

**Comment by bdvholmes** [comment]
I've tidied this up and added very basic support for rooms.

At the moment the interface for defining callbacks with the server is not
aware of specific client connections, so we can't have certain connections
be in certain rooms without overhauling the interface.

E.g.

```js
mockServer.on('say please', function(server) {
  // is it not the case that server == mockServer here?
}
```

In particular because the callback method has no information about the client, it can't subscribe a particular socket connection to one room.

I'm not worried about this because in practice we will have the server on the client-side so there will be one socket connection to the server.

If we need support for multiple sockets at once can I suggest we leave that for another pull request, I'd like to get this merged sooner rather than later.

**Comment by thoov** [comment]
@bdvholmes Let me test it against: https://github.com/thoov/ember-websockets

**Comment by thoov** [comment]
@bdvholmes Also can you update this PR as there is a conflict

**Comment by thoov** [comment]
@bdvholmes 

So I wrote this test:

```js
import Ember from 'ember';
import { module, test } from 'qunit';
import SocketsService from '../../../../services/socket-io';

var component;
var mockServer;
var ConsumerComponent;
var originalSocketIO;

module('Socket.io Service - on(*) tests', {
  setup() {
    var service    = SocketsService.create();
    mockServer = new MockServer('localhost:7100');

    mockServer.on('connection', function(server) {

      // This is called

      mockServer.emit('myNamespace', 'foo');

      mockServer.on('message', function() {

        // This is called

      });
    });

    originalSocketIO = window.io;
    window.io = MockSocketIO;

    ConsumerComponent = Ember.Component.extend({
      socketService: service,
      socket: null
    });
  },
  teardown() {
    window.io = originalSocketIO;

    Ember.run(() => {
      component.destroy();
    });
  }
});

test('that on(open) and on(close) work correctly', assert => {
  var done = assert.async();
  assert.expect(3);

  component = ConsumerComponent.extend({
    init() {
      this._super.apply(this, arguments);
      var socket = this.socketService.socketFor('localhost:7100');

      socket.on('connection', function() {
          // This is never called
      }, this);

      socket.on('myNamespace', function() {
        // This is called

        socket.send('a sample message');
      }, this);
    }
  }).create();
});
```

It seems to be working fairly well except for:

```js
socket.on('connection', function() {
  // This is never called
}, this);
```

I am trying to debug why this is not being called

**Comment by bdvholmes** [comment]
If this is still something we're still happy to pursue, expect to see this brought up-to-date this weekend.

**Comment by calflegal** [comment]
:+1:  this would be very helpful!

**Comment by samselikoff** [comment]
would be so great

**Comment by thoov** [comment]
@bdvholmes there have been some major changes since this was originally opened. It might be easiest to simply start from scratch. I can help with adding io support as it was already in my roadmap.

**Comment by bdvholmes** [comment]
@thoov, thanks I made a start over the weekend - I'll let you know if I have any questions. I'll close this pull request and submit a new one with the other code.

I put together an API check list from the socket.io docs, I don't think we have to cover it all straight away for a v1 but I'm going to bass some tests on the following:

# API

## Client

- [ ] io()
- [ ] io('http://localhost')
- [ ] io.connect('http://localhost')
- [ ] socket.on('connect', function() { // stuff })
- [ ] socket.on('news', function(data) { // stuff })
- [ ] socket.on('message', function(data) { // stuff })
- [ ] socket.on('disconnect', function(data) { // stuff })
- [ ] socket.emit('hi!')});
- [ ] socket.emit('my other event', { my: 'data' });
- [ ] socket.emit('ferret', 'tobi', function (data) { console.log(data); });
- [ ] socket.send('hi!')});

## Server

- [ ] io.on('connection', function(socket) { // stuff })
- [ ] io.of('/chat')
- [ ] io.emit('news', { hello: 'world' });
- [ ] socket.emit('news', { hello: 'world' });
- [ ] socket.on('message', function(data) { // stuff })
- [ ] socket.on('news message', function(data) { // stuff })
- [ ] socket.on('disconnect', function(data) { // stuff })
- [ ] socket.join('some room');
- [ ] socket.leave('some room');
- [ ] io.to('some room').emit('some event');
- [ ] socket.broadcast.emit
- [ ] socket.volatile.emit
- [ ] socket.on('pm', function(id, msg){ socket.broadcast.to(id).emit('my message', msg);
});
- [ ] socket.on('ferret', function (name, fn) { fn('woot'); });
- [ ] io.sockets.emit('hi', 'everyone')

**Comment by thoov** [comment]
@bdvholmes great list. Make sure you include it on the new pr so we can track it there

**Comment by bdvholmes** [comment]
Opening #50 in favour of #23.

**Pull request closed without merging**
