### PR TITLE
Mock Socket.io connections

### PR DESCRIPTION
**Pull request by bdvholmes**
Supercedes #23, given that mock-socket has been refactored since then. This makes the work a bit easier as it happens.

General TODO list gathered from the [Socket.io docs](http://socket.io/docs/), we don't need to do all of it but support for rooms and namespaces should be done before merging:

## Client

- [x] io()
- [x] io('http://localhost')
- [x] io.connect('http://localhost')
- [x] socket.on('connect', function() { // stuff })
- [x] socket.on('error', function(error) { // stuff })
- [x] socket.on('news', function(data) { // stuff })
- [x] socket.on('disconnect', function(data) { // stuff })
- [x] socket.emit('hi!')});
- [x] socket.emit('my other event', { my: 'data' });
- [x] socket.send('hi!')});

## Server

- [x] io.on('connection', function(socket) { // stuff })
- [x] io.of('/chat')
- [x] socket.emit('news', { hello: 'world' });
- [x] socket.on('message', function(data) { // stuff })
- [x] socket.on('news message', function(data) { // stuff })
- [x] socket.on('disconnect', function(data) { // stuff })
- [x] socket.join('some room');
- [x] socket.leave('some room');
- [x] io.to('some room').emit('some event');

## Excluded for now

- [acknowledgements](http://socket.io/docs/#sending-and-getting-data-(acknowledgements)) socket.emit('ferret', 'tobi', function (data) { console.log(data); });
- reconnect events
  - socket.on('reconnect', function(number) { // stuff })
  - socket.on('reconnecting', function(number) { // stuff })
  - socket.on('reconnect_attempt', function() { // stuff })
  - socket.on('reconnect_error', function(error) { // stuff })
  - socket.on('reconnect_failed', function() { // stuff })
- socket.broadcast.emit
- socket.volatile.emit
- socket.on('pm', function(id, msg){ socket.broadcast.to(id).emit('my message', msg);
});
- io.sockets.emit('hi', 'everyone')

### CODE REVIEW

**Comment by bdvholmes** [comment]
Current approach is to

 - create a new SocketIO class to represent the [socket.io Socket](https://github.com/socketio/socket.io-client/blob/master/lib/socket.js#L54).
 - extend the existing server to have some of the socket.io server functionality e.g. emit and rooms support.

**Comment by thoov** [comment]
@bdvholmes This is looking great. I will review it tomorrow

**Comment by thoov** [comment]
For "rooms" I think we should store that information in the network bridge. That way we can extend 

```js
networkBridge.websocketsLookup(this.url, 'room-name');
```

to support fetching all websockets which are in a room.

**Comment by thoov** [comment]
For namespaces:

```js
var nsp = io.of('/my-namespace');
```

`io.of` should simply create a new MockServer with `/my-namespace` as the url

**Comment by bdvholmes** [comment]
Agreed :+1:

**Comment by bdvholmes** [comment]
@thoov I'm pretty happy with this as it is. Let me know what you think.

**Comment by bdvholmes** [comment]
:point_up: might need some help with [this test failure](https://travis-ci.org/thoov/mock-socket/builds/78343440).

**Comment by thoov** [comment]
@bdvholmes I think it has to do with this:

```js
assert.deepEqual('payload', data);
```

`payload` is a string but `data` is an object

**Comment by bdvholmes** [comment]
Yeah I saw that, the test passes on my machine. I believe it had to do with NodeEvent there.
On 1 Sep 2015 22:26, Travis Hoover <notifications@github.com> wrote:@bdvholmes I think it has to do with this:

assert.deepEqual('payload', data);

payload is a string but data is an object

**Comment by thoov** [comment]
@bdvholmes When i run your pr locally via: `npm test` I see the error.
screen shot 2015-09-02 at 9 48 06 am

I will take a look into it and see if I can fix it this morning

**Comment by bdvholmes** [comment]
I was only testing in the browser, got the node tests running and patched it up.

The issue is in getting socket.io event listeners set up, since they expect the callback to be passed the message as opposed to a wrapper `MessageEvent` or `NodeEvent`.

```js
on('message', event => {
  event.data;
});
```

vs

```js
on('message', data => {
  data;
});
```

That [code that breaks this out](https://github.com/thoov/mock-socket/pull/50/files#diff-e6a5b42b2f7a26c840607370aed5301aR113
) wasn't able to detect a NodeEvent so I'll just detect if the argument has `.data` defined on it.

**Comment by thoov** [comment]
Awesome work! Im going to merge it in and play around with it. I will continue to add some more tests

**Comment by calflegal** [comment]
:+1:  This works for me, well done. I was slightly confused about the usage, but I ended up figuring it out by reading the source in combination with the README. Am I right to use this via 
`window.io = MockSocketIO` ?

**Comment by thoov** [comment]
@calflegal Yes. Sorry I haven't updated the readme yet but will do so this week

**Comment by calflegal** [comment]
no problem!

**Comment by samselikoff** [comment]
amazing work yall!

**Pull request merged**
