### PR TITLE
Updating supported node versions

### PR DESCRIPTION
**Pull request by thoov**
Dropping node 6 and adding node 12

### CODE REVIEW

**Comment by Turbo87** [comment]
@thoov dropping supported Node versions should be considered a breaking change. releasing that in a minor version bump is unfortunate since it will suddenly break for people that are still using node 6.

**Comment by thoov** [comment]
@Turbo87 Thanks for calling this out. I reverted the change and then bumped a minor so that folks on the 8.1.* version will not get that and I cut a 9.0.0 version with the node change.

**Comment by Turbo87** [comment]
awesome, thank you! ❤️

**Comment by Turbo87** [comment]
and while I'm here: thanks for writing this lib. it solved a lot of problems for me :)

**Pull request merged**
