### PR TITLE
Use native typed arguments for WebSocket event handlers

### PR DESCRIPTION
**Pull request by Atrue**
Fixes https://github.com/thoov/mock-socket/issues/226

### CODE REVIEW

**Comment by orgads** [comment]
Why did you revert #326?

**Comment by Atrue** [comment]
@orgads Sorry, I forgot to add a detailed message.
I replaced it with native types from typescript to have it consistent with all typescript versions.
Also, `open` and `error` events fire just an Event https://github.com/microsoft/TypeScript/blob/main/lib/lib.dom.d.ts#L17101

**Comment by qmg-akara** [comment]
Thanks for this, when do you plan to publish this to npm? Thanks

**Comment by orgads** [comment]
This is not consistent with `types/ws` package. See https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ws/index.d.ts#L62

The `Event` there is not the native Typescript `Event`, but [this](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ws/index.d.ts#L249).

**Comment by Atrue** [comment]
@orgads `types/ws` is a typed package for https://github.com/websockets/ws, not a native WebSocket. The current implementation doesn't support this now https://github.com/thoov/mock-socket/blob/master/src/event/factory.js

**Comment by Atrue** [comment]
@qmg-akara see https://github.com/thoov/mock-socket/issues/322#issuecomment-927687852

**Comment by Atrue** [comment]
published version `9.0.4`

**Pull request merged**
